spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: false

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET}
    cors:
      front-end: ${CORS_FRONTEND}